# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/initData:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9091:80
    # environment:
    #   - PMA_HOST=db

  node-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
